format_version: v1.0
type: UniqueComponent
attributes: {id: lib_wolfssl}
children:
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: WolfSSL_Crypto_Dependency}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: lib_wolfcrypt}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: lib_wolfcrypt}
- type: ElementPosition
  attributes: {x: '579', y: '479', id: lib_wolfssl}
