format_version: v1.0
type: UniqueComponent
attributes: {id: rtc}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: CALLBACK_API_NAME}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: rtc, value: RTC_Timer32CallbackRegister}
  - type: String
    attributes: {id: COMPARE_SET_API_NAME}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: rtc, value: RTC_Timer32CompareSet}
  - type: String
    attributes: {id: COUNTER_GET_API_NAME}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: rtc, value: RTC_Timer32CounterGet}
  - type: String
    attributes: {id: FREQUENCY_GET_API_NAME}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: rtc, value: RTC_Timer32FrequencyGet}
  - type: String
    attributes: {id: IRQ_ENUM_NAME}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: rtc, value: RTC_IRQn}
  - type: String
    attributes: {id: PERIOD_SET_API_NAME}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: rtc, value: ''}
  - type: Comment
    attributes: {id: RTC_INTERRUPT_ENABLE_COMMENT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Hex
    attributes: {id: RTC_MODE0_EVCTRL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: rtc, value: '0'}
  - type: Hex
    attributes: {id: RTC_MODE0_INTENSET}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: rtc, value: '0'}
  - type: Boolean
    attributes: {id: RTC_MODE0_MATCHCLR}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: KeyValueSet
    attributes: {id: RTC_MODE0_PRESCALER}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '10'}
  - type: Boolean
    attributes: {id: RTC_MODE2_INTERRUPT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: KeyValueSet
    attributes: {id: RTC_MODE2_PRESCALER}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '10'}
  - type: KeyValueSet
    attributes: {id: RTC_MODULE_SELECTION}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
  - type: String
    attributes: {id: TIMER_PERIOD_MAX}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: rtc, value: '0xFFFFFFFF'}
  - type: String
    attributes: {id: TIMER_START_API_NAME}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: rtc, value: RTC_Timer32Start}
  - type: String
    attributes: {id: TIMER_STOP_API_NAME}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: rtc, value: RTC_Timer32Stop}
  - type: Integer
    attributes: {id: TIMER_WIDTH}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: rtc, value: '32'}
- type: ElementPosition
  attributes: {x: '515', y: '80', id: rtc}
